---
title: "Resumé"
author: "Tiara Verweij"
date: "29-5-2021"
output:
  html_document:
    df_print: paged
---

-------------------     ----------------------------
Dinkelwijk 14                tiaraverweij@gmail.com
3831 MG                      linkedin: TiaraVerweij
Leusden                      06-36073408
-------------------     ----------------------------


## About me

I am a hardworking student with an eye for detail and a passion for biomedical research. I like to show my creative side when working on research. My strong qualities are my perseverance, accuracy, thinking in solutions, my social skills and my honesty.

## My long term goals

I am currently working on obtaining my Bachelor's degree in Sciences. In the future, I plan to find a challenging job in Research and would like to find a job where I can further develop myself in data science.

Education
---------

2017-2022 (expected)
:   **Bachelor, Sciences**; Hogeschool Utrecht (Utrecht)

    *Minor: Data Science for Biology*     
    *Specialisation: Biomolecular Research*

2012-2017
:   **Havo, Nature and Technique**; Het Nieuwe Eemland
     (Amersfoort)

    *Course: physics, biology, science and math*
    
Job Experience
----------

**Administrative Staff Member - ABN AMRO Bank **

Perform administrative work in various systems. In addition, I have mail contact with customers regarding questions about their contract. 

**Manager in a restaurant**

Opening and closing the building, managing colleagues and helping guests with problems. 


## Previous research

**Project Lectorate**
This is my current project. I am building a script where data sets from a transcription analysis can be downloaded via a GSE/SRA number and then a summarised experiment can be made. 

**Project Genes & proteins**
This research was about the role of the immune system during a viral infection. The aim was to find out more about Interleukin-8, which plays a role in the infection with the RS virus. 

**Project Pharmacon**
This research focused on the effect of the pharmaceutical compound Lithium on the C. Elegans in relation to Alzheimer's disease. 

**Project Biomolecular Research**
This research dealt with the absorption of the fatty acids EPA and DHA in muscle cells. It also examined where the fatty acids go after absorption.


Technical Experience
--------------------

Building my own Shiny App
:   I am currently working on my own shiny app. 


Programming Languages
:   **R** R is what I use most for programming. I have been working with R for about 6 months now and I have had several assignments on R. These can also be found on my Github page. (link below).

: https://github.com/tiara150/Portfolio_DSFB2.git

